// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    Default: typeof import('./src/layouts/default.vue')['default']
    DemoFormLogin: typeof import('./src/components/DemoFormLogin.vue')['default']
    DemoFormPersonal: typeof import('./src/components/DemoFormPersonal.vue')['default']
    GreetModal: typeof import('./src/components/GreetModal.vue')['default']
    Header: typeof import('./src/layouts/components/Header.vue')['default']
    HeaderBreadcrumb: typeof import('./src/layouts/components/HeaderBreadcrumb.vue')['default']
    HeaderUserMenu: typeof import('./src/layouts/components/HeaderUserMenu.vue')['default']
    LoginLayout: typeof import('./src/layouts/loginLayout.vue')['default']
    MButton: typeof import('./src/components/MButton.vue')['default']
    MEmpty: typeof import('./src/components/MEmpty.vue')['default']
    MInputNumber: typeof import('./src/components/MInputNumber.vue')['default']
    MProgress: typeof import('./src/components/MProgress.vue')['default']
    MResult: typeof import('./src/components/MResult.vue')['default']
    MTag: typeof import('./src/components/MTag.vue')['default']
    RoleDetail: typeof import('./src/components/RoleDetail.vue')['default']
    RoleDetailAdd: typeof import('./src/components/RoleDetailAdd.vue')['default']
    RoleDetailEdit: typeof import('./src/components/RoleDetailEdit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./src/layouts/components/Sider.vue')['default']
    SiderMenu: typeof import('./src/layouts/components/SiderMenu.vue')['default']
    SiderMenuIcon: typeof import('./src/layouts/components/SiderMenuIcon.vue')['default']
    SiderMenuItem: typeof import('./src/layouts/components/SiderMenuItem.vue')['default']
    SiderSubMenuItem: typeof import('./src/layouts/components/SiderSubMenuItem.vue')['default']
    StepFormAudit: typeof import('./src/components/StepFormAudit.vue')['default']
    StepFormProject: typeof import('./src/components/StepFormProject.vue')['default']
    StepFormResult: typeof import('./src/components/StepFormResult.vue')['default']
    TeamsAddModal: typeof import('./src/components/TeamsAddModal.vue')['default']
    TeamsDetail: typeof import('./src/components/TeamsDetail.vue')['default']
    TeamsEditModal: typeof import('./src/components/TeamsEditModal.vue')['default']
  }
}

export {}
